sudo: required
language: r
cran: https://cran.rstudio.com/
matrix:
  include:
  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
    - Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    r_binary_packages:
    - covr
    r_github_packages:
    - jimhester/lintr
    before_script:
    - Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        packages:
        - libgdal1-dev
        - libproj-dev
    before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
    - Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
  - os: osx
    osx_image: xcode8.2
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_script:
    - Rscript -e 'install.packages(c("Rcpp", "dplyr"), type = "source")'
r_build_args: '--compact-vignettes="gs+qpdf"'
r_check_args: '--as-cran'
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - development
