# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

habConnRcpp <- function(cost, nrow, ncol, hab, no_data, distinctValues, increment = 1.0) {
    .Call('grainscape2_habConnRcpp', PACKAGE = 'grainscape2', cost, nrow, ncol, hab, no_data, distinctValues, increment)
}

