# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HabConnEngine <- function(cost, nrow, ncol, hab, no_data, voronoi_map, link_map, patch_map) {
    .Call('grainscape2_HabConnEngine', PACKAGE = 'grainscape2', cost, nrow, ncol, hab, no_data, voronoi_map, link_map, patch_map)
}

