# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Habitat connectivity
#'
#' DESCRIPTION NEEDED
#'
#' @param cost              DESCRIPTION NEEDED
#'
#' @param nrow              DESCRIPTION NEEDED
#'
#' @param ncol              DESCRIPTION NEEDED
#'
#' @param hab               DESCRIPTION NEEDED
#'
#' @param no_data           DESCRIPTION NEEDED
#'
#' @param distinctValues    DESCRIPTION NEEDED
#'
#' @param threshold         DESCRIPTION NEEDED (default \code{1e-4}).
#'
#' @author Sam Doctolero
#' @docType methods
#' @export
#' @rdname habConnRcpp
habConnRcpp <- function(cost, nrow, ncol, hab, no_data, distinctValues, threshold = 0.0001) {
    .Call('grainscape2_habConnRcpp', PACKAGE = 'grainscape2', cost, nrow, ncol, hab, no_data, distinctValues, threshold)
}

